FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim

WORKDIR /opt/ui
COPY ui /opt/ui

RUN uv sync

EXPOSE 8501

CMD ["uv", "run", "streamlit", "run", "src/ui/main.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true", "--server.enableCORS=false"]
